/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  net.minecraft.resources.ResourceLocation
 *  net.minecraft.sounds.SoundEvent
 *  net.minecraftforge.registries.DeferredRegister
 *  net.minecraftforge.registries.ForgeRegistries
 *  net.minecraftforge.registries.IForgeRegistry
 *  net.minecraftforge.registries.RegistryObject
 */
package com.github.alexthe666.alexsmobs.misc;

import net.minecraft.resources.ResourceLocation;
import net.minecraft.sounds.SoundEvent;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.IForgeRegistry;
import net.minecraftforge.registries.RegistryObject;

public class AMSoundRegistry {
    public static final DeferredRegister<SoundEvent> DEF_REG = DeferredRegister.create((IForgeRegistry)ForgeRegistries.SOUND_EVENTS, (String)"alexsmobs");
    public static final RegistryObject<SoundEvent> GRIZZLY_BEAR_IDLE = AMSoundRegistry.createSoundEvent("grizzly_bear_idle");
    public static final RegistryObject<SoundEvent> GRIZZLY_BEAR_HURT = AMSoundRegistry.createSoundEvent("grizzly_bear_hurt");
    public static final RegistryObject<SoundEvent> GRIZZLY_BEAR_DIE = AMSoundRegistry.createSoundEvent("grizzly_bear_die");
    public static final RegistryObject<SoundEvent> BEAR_DUST = AMSoundRegistry.createSoundEvent("bear_dust");
    public static final RegistryObject<SoundEvent> ROADRUNNER_IDLE = AMSoundRegistry.createSoundEvent("roadrunner_idle");
    public static final RegistryObject<SoundEvent> ROADRUNNER_HURT = AMSoundRegistry.createSoundEvent("roadrunner_hurt");
    public static final RegistryObject<SoundEvent> ROADRUNNER_MEEP = AMSoundRegistry.createSoundEvent("roadrunner_meep");
    public static final RegistryObject<SoundEvent> GAZELLE_HURT = AMSoundRegistry.createSoundEvent("gazelle_hurt");
    public static final RegistryObject<SoundEvent> CROCODILE_IDLE = AMSoundRegistry.createSoundEvent("crocodile_idle");
    public static final RegistryObject<SoundEvent> CROCODILE_HURT = AMSoundRegistry.createSoundEvent("crocodile_hurt");
    public static final RegistryObject<SoundEvent> CROCODILE_BITE = AMSoundRegistry.createSoundEvent("crocodile_bite");
    public static final RegistryObject<SoundEvent> CROCODILE_BABY = AMSoundRegistry.createSoundEvent("crocodile_baby");
    public static final RegistryObject<SoundEvent> FLY_IDLE = AMSoundRegistry.createSoundEvent("fly_idle");
    public static final RegistryObject<SoundEvent> FLY_HURT = AMSoundRegistry.createSoundEvent("fly_hurt");
    public static final RegistryObject<SoundEvent> HUMMINGBIRD_IDLE = AMSoundRegistry.createSoundEvent("hummingbird_idle");
    public static final RegistryObject<SoundEvent> HUMMINGBIRD_HURT = AMSoundRegistry.createSoundEvent("hummingbird_hurt");
    public static final RegistryObject<SoundEvent> HUMMINGBIRD_LOOP = AMSoundRegistry.createSoundEvent("hummingbird_loop");
    public static final RegistryObject<SoundEvent> ORCA_IDLE = AMSoundRegistry.createSoundEvent("orca_idle");
    public static final RegistryObject<SoundEvent> ORCA_HURT = AMSoundRegistry.createSoundEvent("orca_hurt");
    public static final RegistryObject<SoundEvent> ORCA_DIE = AMSoundRegistry.createSoundEvent("orca_die");
    public static final RegistryObject<SoundEvent> GORILLA_IDLE = AMSoundRegistry.createSoundEvent("gorilla_idle");
    public static final RegistryObject<SoundEvent> GORILLA_HURT = AMSoundRegistry.createSoundEvent("gorilla_hurt");
    public static final RegistryObject<SoundEvent> MOSQUITO_LOOP = AMSoundRegistry.createSoundEvent("mosquito_loop");
    public static final RegistryObject<SoundEvent> MOSQUITO_HURT = AMSoundRegistry.createSoundEvent("mosquito_hurt");
    public static final RegistryObject<SoundEvent> MOSQUITO_DIE = AMSoundRegistry.createSoundEvent("mosquito_die");
    public static final RegistryObject<SoundEvent> RATTLESNAKE_LOOP = AMSoundRegistry.createSoundEvent("rattlesnake_loop");
    public static final RegistryObject<SoundEvent> RATTLESNAKE_HURT = AMSoundRegistry.createSoundEvent("rattlesnake_hurt");
    public static final RegistryObject<SoundEvent> RATTLESNAKE_ATTACK = AMSoundRegistry.createSoundEvent("rattlesnake_attack");
    public static final RegistryObject<SoundEvent> ENDERGRADE_IDLE = AMSoundRegistry.createSoundEvent("endergrade_idle");
    public static final RegistryObject<SoundEvent> ENDERGRADE_HURT = AMSoundRegistry.createSoundEvent("endergrade_hurt");
    public static final RegistryObject<SoundEvent> LOBSTER_HURT = AMSoundRegistry.createSoundEvent("lobster_hurt");
    public static final RegistryObject<SoundEvent> LOBSTER_ATTACK = AMSoundRegistry.createSoundEvent("lobster_attack");
    public static final RegistryObject<SoundEvent> KOMODO_DRAGON_IDLE = AMSoundRegistry.createSoundEvent("komodo_dragon_idle");
    public static final RegistryObject<SoundEvent> KOMODO_DRAGON_HURT = AMSoundRegistry.createSoundEvent("komodo_dragon_hurt");
    public static final RegistryObject<SoundEvent> SUNBIRD_IDLE = AMSoundRegistry.createSoundEvent("sunbird_idle");
    public static final RegistryObject<SoundEvent> SUNBIRD_HURT = AMSoundRegistry.createSoundEvent("sunbird_hurt");
    public static final RegistryObject<SoundEvent> CAPUCHIN_MONKEY_IDLE = AMSoundRegistry.createSoundEvent("capuchin_monkey_idle");
    public static final RegistryObject<SoundEvent> CAPUCHIN_MONKEY_HURT = AMSoundRegistry.createSoundEvent("capuchin_monkey_hurt");
    public static final RegistryObject<SoundEvent> BONE_SERPENT_IDLE = AMSoundRegistry.createSoundEvent("bone_serpent_idle");
    public static final RegistryObject<SoundEvent> BONE_SERPENT_HURT = AMSoundRegistry.createSoundEvent("bone_serpent_hurt");
    public static final RegistryObject<SoundEvent> CENTIPEDE_WALK = AMSoundRegistry.createSoundEvent("centipede_walk");
    public static final RegistryObject<SoundEvent> CENTIPEDE_HURT = AMSoundRegistry.createSoundEvent("centipede_hurt");
    public static final RegistryObject<SoundEvent> CENTIPEDE_ATTACK = AMSoundRegistry.createSoundEvent("centipede_attack");
    public static final RegistryObject<SoundEvent> WARPED_TOAD_IDLE = AMSoundRegistry.createSoundEvent("warped_toad_idle");
    public static final RegistryObject<SoundEvent> WARPED_TOAD_HURT = AMSoundRegistry.createSoundEvent("warped_toad_hurt");
    public static final RegistryObject<SoundEvent> MOOSE_IDLE = AMSoundRegistry.createSoundEvent("moose_idle");
    public static final RegistryObject<SoundEvent> MOOSE_HURT = AMSoundRegistry.createSoundEvent("moose_hurt");
    public static final RegistryObject<SoundEvent> MOOSE_JOSTLE = AMSoundRegistry.createSoundEvent("moose_jostle");
    public static final RegistryObject<SoundEvent> MIMICUBE_JUMP = AMSoundRegistry.createSoundEvent("mimicube_jump");
    public static final RegistryObject<SoundEvent> MIMICUBE_HURT = AMSoundRegistry.createSoundEvent("mimicube_hurt");
    public static final RegistryObject<SoundEvent> RACCOON_IDLE = AMSoundRegistry.createSoundEvent("raccoon_idle");
    public static final RegistryObject<SoundEvent> RACCOON_HURT = AMSoundRegistry.createSoundEvent("raccoon_hurt");
    public static final RegistryObject<SoundEvent> MARACA = AMSoundRegistry.createSoundEvent("maraca");
    public static final RegistryObject<SoundEvent> LA_CUCARACHA = AMSoundRegistry.createSoundEvent("la_cucaracha");
    public static final RegistryObject<SoundEvent> SEAL_IDLE = AMSoundRegistry.createSoundEvent("seal_idle");
    public static final RegistryObject<SoundEvent> SEAL_HURT = AMSoundRegistry.createSoundEvent("seal_hurt");
    public static final RegistryObject<SoundEvent> COCKROACH_HURT = AMSoundRegistry.createSoundEvent("cockroach_hurt");
    public static final RegistryObject<SoundEvent> SHOEBILL_HURT = AMSoundRegistry.createSoundEvent("shoebill_hurt");
    public static final RegistryObject<SoundEvent> ELEPHANT_IDLE = AMSoundRegistry.createSoundEvent("elephant_idle");
    public static final RegistryObject<SoundEvent> ELEPHANT_HURT = AMSoundRegistry.createSoundEvent("elephant_hurt");
    public static final RegistryObject<SoundEvent> ELEPHANT_DIE = AMSoundRegistry.createSoundEvent("elephant_die");
    public static final RegistryObject<SoundEvent> ELEPHANT_TRUMPET = AMSoundRegistry.createSoundEvent("elephant_trumpet");
    public static final RegistryObject<SoundEvent> ELEPHANT_WALK = AMSoundRegistry.createSoundEvent("elephant_walk");
    public static final RegistryObject<SoundEvent> SOUL_VULTURE_IDLE = AMSoundRegistry.createSoundEvent("soul_vulture_idle");
    public static final RegistryObject<SoundEvent> SOUL_VULTURE_HURT = AMSoundRegistry.createSoundEvent("soul_vulture_hurt");
    public static final RegistryObject<SoundEvent> SNOW_LEOPARD_IDLE = AMSoundRegistry.createSoundEvent("snow_leopard_idle");
    public static final RegistryObject<SoundEvent> SNOW_LEOPARD_HURT = AMSoundRegistry.createSoundEvent("snow_leopard_hurt");
    public static final RegistryObject<SoundEvent> SPECTRE_IDLE = AMSoundRegistry.createSoundEvent("spectre_idle");
    public static final RegistryObject<SoundEvent> SPECTRE_HURT = AMSoundRegistry.createSoundEvent("spectre_hurt");
    public static final RegistryObject<SoundEvent> CROW_IDLE = AMSoundRegistry.createSoundEvent("crow_idle");
    public static final RegistryObject<SoundEvent> CROW_HURT = AMSoundRegistry.createSoundEvent("crow_hurt");
    public static final RegistryObject<SoundEvent> ALLIGATOR_SNAPPING_TURTLE_IDLE = AMSoundRegistry.createSoundEvent("alligator_snapping_turtle_idle");
    public static final RegistryObject<SoundEvent> ALLIGATOR_SNAPPING_TURTLE_HURT = AMSoundRegistry.createSoundEvent("alligator_snapping_turtle_hurt");
    public static final RegistryObject<SoundEvent> MUNGUS_IDLE = AMSoundRegistry.createSoundEvent("mungus_idle");
    public static final RegistryObject<SoundEvent> MUNGUS_HURT = AMSoundRegistry.createSoundEvent("mungus_hurt");
    public static final RegistryObject<SoundEvent> MUNGUS_LASER_END = AMSoundRegistry.createSoundEvent("mungus_laser_end");
    public static final RegistryObject<SoundEvent> MUNGUS_LASER_LOOP = AMSoundRegistry.createSoundEvent("mungus_laser_loop");
    public static final RegistryObject<SoundEvent> MUNGUS_LASER_GROW = AMSoundRegistry.createSoundEvent("mungus_laser_grow");
    public static final RegistryObject<SoundEvent> MANTIS_SHRIMP_SNAP = AMSoundRegistry.createSoundEvent("mantis_shrimp_snap");
    public static final RegistryObject<SoundEvent> MANTIS_SHRIMP_HURT = AMSoundRegistry.createSoundEvent("mantis_shrimp_hurt");
    public static final RegistryObject<SoundEvent> GUSTER_IDLE = AMSoundRegistry.createSoundEvent("guster_idle");
    public static final RegistryObject<SoundEvent> GUSTER_HURT = AMSoundRegistry.createSoundEvent("guster_hurt");
    public static final RegistryObject<SoundEvent> WARPED_MOSCO_IDLE = AMSoundRegistry.createSoundEvent("warped_mosco_idle");
    public static final RegistryObject<SoundEvent> WARPED_MOSCO_HURT = AMSoundRegistry.createSoundEvent("warped_mosco_hurt");
    public static final RegistryObject<SoundEvent> STRADDLER_IDLE = AMSoundRegistry.createSoundEvent("straddler_idle");
    public static final RegistryObject<SoundEvent> STRADDLER_HURT = AMSoundRegistry.createSoundEvent("straddler_hurt");
    public static final RegistryObject<SoundEvent> EMU_IDLE = AMSoundRegistry.createSoundEvent("emu_idle");
    public static final RegistryObject<SoundEvent> EMU_HURT = AMSoundRegistry.createSoundEvent("emu_hurt");
    public static final RegistryObject<SoundEvent> PLATYPUS_IDLE = AMSoundRegistry.createSoundEvent("platypus_idle");
    public static final RegistryObject<SoundEvent> PLATYPUS_HURT = AMSoundRegistry.createSoundEvent("platypus_hurt");
    public static final RegistryObject<SoundEvent> DROPBEAR_IDLE = AMSoundRegistry.createSoundEvent("dropbear_idle");
    public static final RegistryObject<SoundEvent> DROPBEAR_HURT = AMSoundRegistry.createSoundEvent("dropbear_hurt");
    public static final RegistryObject<SoundEvent> TASMANIAN_DEVIL_IDLE = AMSoundRegistry.createSoundEvent("tasmanian_devil_idle");
    public static final RegistryObject<SoundEvent> TASMANIAN_DEVIL_HURT = AMSoundRegistry.createSoundEvent("tasmanian_devil_hurt");
    public static final RegistryObject<SoundEvent> TASMANIAN_DEVIL_ROAR = AMSoundRegistry.createSoundEvent("tasmanian_devil_roar");
    public static final RegistryObject<SoundEvent> KANGAROO_IDLE = AMSoundRegistry.createSoundEvent("kangaroo_idle");
    public static final RegistryObject<SoundEvent> KANGAROO_HURT = AMSoundRegistry.createSoundEvent("kangaroo_hurt");
    public static final RegistryObject<SoundEvent> CACHALOT_WHALE_IDLE = AMSoundRegistry.createSoundEvent("cachalot_whale_idle");
    public static final RegistryObject<SoundEvent> CACHALOT_WHALE_HURT = AMSoundRegistry.createSoundEvent("cachalot_whale_hurt");
    public static final RegistryObject<SoundEvent> CACHALOT_WHALE_CLICK = AMSoundRegistry.createSoundEvent("cachalot_whale_click");
    public static final RegistryObject<SoundEvent> LEAFCUTTER_ANT_HURT = AMSoundRegistry.createSoundEvent("leafcutter_ant_hurt");
    public static final RegistryObject<SoundEvent> LEAFCUTTER_ANT_QUEEN_HURT = AMSoundRegistry.createSoundEvent("leafcutter_ant_queen_hurt");
    public static final RegistryObject<SoundEvent> ENDERIOPHAGE_HURT = AMSoundRegistry.createSoundEvent("enderiophage_hurt");
    public static final RegistryObject<SoundEvent> ENDERIOPHAGE_SQUISH = AMSoundRegistry.createSoundEvent("enderiophage_squish");
    public static final RegistryObject<SoundEvent> ENDERIOPHAGE_WALK = AMSoundRegistry.createSoundEvent("enderiophage_walk");
    public static final RegistryObject<SoundEvent> MUSIC_DISC_THIME = AMSoundRegistry.createSoundEvent("music_disc_thime");
    public static final RegistryObject<SoundEvent> BALD_EAGLE_IDLE = AMSoundRegistry.createSoundEvent("bald_eagle_idle");
    public static final RegistryObject<SoundEvent> BALD_EAGLE_HURT = AMSoundRegistry.createSoundEvent("bald_eagle_hurt");
    public static final RegistryObject<SoundEvent> TIGER_IDLE = AMSoundRegistry.createSoundEvent("tiger_idle");
    public static final RegistryObject<SoundEvent> TIGER_HURT = AMSoundRegistry.createSoundEvent("tiger_hurt");
    public static final RegistryObject<SoundEvent> TIGER_ANGRY = AMSoundRegistry.createSoundEvent("tiger_angry");
    public static final RegistryObject<SoundEvent> TARANTULA_HAWK_WING = AMSoundRegistry.createSoundEvent("tarantula_hawk_wing");
    public static final RegistryObject<SoundEvent> TARANTULA_HAWK_HURT = AMSoundRegistry.createSoundEvent("tarantula_hawk_hurt");
    public static final RegistryObject<SoundEvent> MUSIC_WORMBOSS = AMSoundRegistry.createSoundEvent("music_wormboss");
    public static final RegistryObject<SoundEvent> VOID_WORM_IDLE = AMSoundRegistry.createSoundEvent("void_worm_idle");
    public static final RegistryObject<SoundEvent> VOID_WORM_HURT = AMSoundRegistry.createSoundEvent("void_worm_hurt");
    public static final RegistryObject<SoundEvent> VOID_PORTAL_CLOSE = AMSoundRegistry.createSoundEvent("void_portal_close");
    public static final RegistryObject<SoundEvent> VOID_PORTAL_OPEN = AMSoundRegistry.createSoundEvent("void_portal_open");
    public static final RegistryObject<SoundEvent> MIMIC_OCTOPUS_IDLE = AMSoundRegistry.createSoundEvent("mimic_octopus_idle");
    public static final RegistryObject<SoundEvent> MIMIC_OCTOPUS_HURT = AMSoundRegistry.createSoundEvent("mimic_octopus_hurt");
    public static final RegistryObject<SoundEvent> MUSIC_DISC_DAZE = AMSoundRegistry.createSoundEvent("music_disc_daze");
    public static final RegistryObject<SoundEvent> SEAGULL_IDLE = AMSoundRegistry.createSoundEvent("seagull_idle");
    public static final RegistryObject<SoundEvent> SEAGULL_HURT = AMSoundRegistry.createSoundEvent("seagull_hurt");
    public static final RegistryObject<SoundEvent> FROSTSTALKER_IDLE = AMSoundRegistry.createSoundEvent("froststalker_idle");
    public static final RegistryObject<SoundEvent> FROSTSTALKER_HURT = AMSoundRegistry.createSoundEvent("froststalker_hurt");
    public static final RegistryObject<SoundEvent> TUSKLIN_IDLE = AMSoundRegistry.createSoundEvent("tusklin_idle");
    public static final RegistryObject<SoundEvent> TUSKLIN_HURT = AMSoundRegistry.createSoundEvent("tusklin_hurt");
    public static final RegistryObject<SoundEvent> LAVIATHAN_IDLE = AMSoundRegistry.createSoundEvent("laviathan_idle");
    public static final RegistryObject<SoundEvent> LAVIATHAN_HURT = AMSoundRegistry.createSoundEvent("laviathan_hurt");
    public static final RegistryObject<SoundEvent> COSMAW_IDLE = AMSoundRegistry.createSoundEvent("cosmaw_idle");
    public static final RegistryObject<SoundEvent> COSMAW_HURT = AMSoundRegistry.createSoundEvent("cosmaw_hurt");
    public static final RegistryObject<SoundEvent> TOUCAN_IDLE = AMSoundRegistry.createSoundEvent("toucan_idle");
    public static final RegistryObject<SoundEvent> TOUCAN_HURT = AMSoundRegistry.createSoundEvent("toucan_hurt");
    public static final RegistryObject<SoundEvent> MANED_WOLF_IDLE = AMSoundRegistry.createSoundEvent("maned_wolf_idle");
    public static final RegistryObject<SoundEvent> MANED_WOLF_HURT = AMSoundRegistry.createSoundEvent("maned_wolf_hurt");
    public static final RegistryObject<SoundEvent> ANACONDA_SLITHER = AMSoundRegistry.createSoundEvent("anaconda_slither");
    public static final RegistryObject<SoundEvent> ANACONDA_HURT = AMSoundRegistry.createSoundEvent("anaconda_hurt");
    public static final RegistryObject<SoundEvent> ANACONDA_ATTACK = AMSoundRegistry.createSoundEvent("anaconda_attack");
    public static final RegistryObject<SoundEvent> VINE_LASSO = AMSoundRegistry.createSoundEvent("vine_lasso");
    public static final RegistryObject<SoundEvent> ANTEATER_HURT = AMSoundRegistry.createSoundEvent("anteater_hurt");
    public static final RegistryObject<SoundEvent> ROCKY_ROLLER_IDLE = AMSoundRegistry.createSoundEvent("rocky_roller_idle");
    public static final RegistryObject<SoundEvent> ROCKY_ROLLER_HURT = AMSoundRegistry.createSoundEvent("rocky_roller_hurt");
    public static final RegistryObject<SoundEvent> ROCKY_ROLLER_EARTHQUAKE = AMSoundRegistry.createSoundEvent("rocky_roller_earthquake");
    public static final RegistryObject<SoundEvent> GELADA_MONKEY_IDLE = AMSoundRegistry.createSoundEvent("gelada_monkey_idle");
    public static final RegistryObject<SoundEvent> GELADA_MONKEY_HURT = AMSoundRegistry.createSoundEvent("gelada_monkey_hurt");
    public static final RegistryObject<SoundEvent> FLUTTER_IDLE = AMSoundRegistry.createSoundEvent("flutter_idle");
    public static final RegistryObject<SoundEvent> FLUTTER_HURT = AMSoundRegistry.createSoundEvent("flutter_hurt");
    public static final RegistryObject<SoundEvent> FLUTTER_FLAP = AMSoundRegistry.createSoundEvent("flutter_flap");
    public static final RegistryObject<SoundEvent> FLUTTER_NO = AMSoundRegistry.createSoundEvent("flutter_no");
    public static final RegistryObject<SoundEvent> FLUTTER_YES = AMSoundRegistry.createSoundEvent("flutter_yes");
    public static final RegistryObject<SoundEvent> JERBOA_IDLE = AMSoundRegistry.createSoundEvent("jerboa_idle");
    public static final RegistryObject<SoundEvent> JERBOA_HURT = AMSoundRegistry.createSoundEvent("jerboa_hurt");
    public static final RegistryObject<SoundEvent> TERRAPIN_HURT = AMSoundRegistry.createSoundEvent("terrapin_hurt");
    public static final RegistryObject<SoundEvent> COMB_JELLY_HURT = AMSoundRegistry.createSoundEvent("comb_jelly_hurt");
    public static final RegistryObject<SoundEvent> COSMIC_COD_HURT = AMSoundRegistry.createSoundEvent("cosmic_cod_hurt");
    public static final RegistryObject<SoundEvent> MOSQUITO_CAPSID_CONVERT = AMSoundRegistry.createSoundEvent("mosquito_capsid_convert");
    public static final RegistryObject<SoundEvent> GIANT_SQUID_GAMES = AMSoundRegistry.createSoundEvent("giant_squid_games");
    public static final RegistryObject<SoundEvent> APRIL_FOOLS_SCREAM = AMSoundRegistry.createSoundEvent("april_fools_scream");
    public static final RegistryObject<SoundEvent> APRIL_FOOLS_POWER_OUTAGE = AMSoundRegistry.createSoundEvent("april_fools_power_outage");
    public static final RegistryObject<SoundEvent> APRIL_FOOLS_MUSIC_BOX = AMSoundRegistry.createSoundEvent("april_fools_music_box");
    public static final RegistryObject<SoundEvent> BUNFUNGUS_IDLE = AMSoundRegistry.createSoundEvent("bunfungus_idle");
    public static final RegistryObject<SoundEvent> BUNFUNGUS_HURT = AMSoundRegistry.createSoundEvent("bunfungus_hurt");
    public static final RegistryObject<SoundEvent> BUNFUNGUS_ATTACK = AMSoundRegistry.createSoundEvent("bunfungus_attack");
    public static final RegistryObject<SoundEvent> BUNFUNGUS_JUMP = AMSoundRegistry.createSoundEvent("bunfungus_jump");
    public static final RegistryObject<SoundEvent> BISON_IDLE = AMSoundRegistry.createSoundEvent("bison_idle");
    public static final RegistryObject<SoundEvent> BISON_HURT = AMSoundRegistry.createSoundEvent("bison_hurt");
    public static final RegistryObject<SoundEvent> GIANT_SQUID_HURT = AMSoundRegistry.createSoundEvent("giant_squid_hurt");
    public static final RegistryObject<SoundEvent> GIANT_SQUID_TENTACLE = AMSoundRegistry.createSoundEvent("giant_squid_tentacle");
    public static final RegistryObject<SoundEvent> DEVILS_HOLE_PUPFISH_HURT = AMSoundRegistry.createSoundEvent("devils_hole_pupfish_hurt");
    public static final RegistryObject<SoundEvent> SKELEWAG_HURT = AMSoundRegistry.createSoundEvent("skelewag_hurt");
    public static final RegistryObject<SoundEvent> SKELEWAG_IDLE = AMSoundRegistry.createSoundEvent("skelewag_idle");
    public static final RegistryObject<SoundEvent> RAIN_FROG_HURT = AMSoundRegistry.createSoundEvent("rain_frog_hurt");
    public static final RegistryObject<SoundEvent> RAIN_FROG_IDLE = AMSoundRegistry.createSoundEvent("rain_frog_idle");
    public static final RegistryObject<SoundEvent> POTOO_HURT = AMSoundRegistry.createSoundEvent("potoo_hurt");
    public static final RegistryObject<SoundEvent> POTOO_CALL = AMSoundRegistry.createSoundEvent("potoo_call");
    public static final RegistryObject<SoundEvent> MUDSKIPPER_HURT = AMSoundRegistry.createSoundEvent("mudskipper_hurt");
    public static final RegistryObject<SoundEvent> MUDSKIPPER_WALK = AMSoundRegistry.createSoundEvent("mudskipper_walk");
    public static final RegistryObject<SoundEvent> MUDSKIPPER_SPIT = AMSoundRegistry.createSoundEvent("mudskipper_spit");
    public static final RegistryObject<SoundEvent> RHINOCEROS_IDLE = AMSoundRegistry.createSoundEvent("rhinoceros_idle");
    public static final RegistryObject<SoundEvent> RHINOCEROS_HURT = AMSoundRegistry.createSoundEvent("rhinoceros_hurt");
    public static final RegistryObject<SoundEvent> SUGAR_GLIDER_IDLE = AMSoundRegistry.createSoundEvent("sugar_glider_idle");
    public static final RegistryObject<SoundEvent> SUGAR_GLIDER_HURT = AMSoundRegistry.createSoundEvent("sugar_glider_hurt");
    public static final RegistryObject<SoundEvent> FARSEER_HURT = AMSoundRegistry.createSoundEvent("farseer_hurt");
    public static final RegistryObject<SoundEvent> FARSEER_IDLE = AMSoundRegistry.createSoundEvent("farseer_idle");
    public static final RegistryObject<SoundEvent> FARSEER_EMERGE = AMSoundRegistry.createSoundEvent("farseer_emerge");
    public static final RegistryObject<SoundEvent> FARSEER_BEAM = AMSoundRegistry.createSoundEvent("farseer_beam");
    public static final RegistryObject<SoundEvent> TRANSMUTE_ITEM = AMSoundRegistry.createSoundEvent("transmute_item");
    public static final RegistryObject<SoundEvent> SKREECHER_HURT = AMSoundRegistry.createSoundEvent("skreecher_hurt");
    public static final RegistryObject<SoundEvent> SKREECHER_CALL = AMSoundRegistry.createSoundEvent("skreecher_call");
    public static final RegistryObject<SoundEvent> SKREECHER_DETECT = AMSoundRegistry.createSoundEvent("skreecher_detect");
    public static final RegistryObject<SoundEvent> SKREECHER_CLAP = AMSoundRegistry.createSoundEvent("skreecher_clap");
    public static final RegistryObject<SoundEvent> SCULK_BOOMER = AMSoundRegistry.createSoundEvent("sculk_boomer");
    public static final RegistryObject<SoundEvent> SCULK_BOOMER_FART = AMSoundRegistry.createSoundEvent("sculk_boomer_fart");
    public static final RegistryObject<SoundEvent> UNDERMINER_IDLE = AMSoundRegistry.createSoundEvent("underminer_idle");
    public static final RegistryObject<SoundEvent> UNDERMINER_HURT = AMSoundRegistry.createSoundEvent("underminer_hurt");
    public static final RegistryObject<SoundEvent> UNDERMINER_STEP = AMSoundRegistry.createSoundEvent("underminer_step");
    public static final RegistryObject<SoundEvent> MURMUR_HURT = AMSoundRegistry.createSoundEvent("murmur_hurt");
    public static final RegistryObject<SoundEvent> MURMUR_IDLE = AMSoundRegistry.createSoundEvent("murmur_idle");
    public static final RegistryObject<SoundEvent> MURMUR_NECK = AMSoundRegistry.createSoundEvent("murmur_neck");
    public static final RegistryObject<SoundEvent> MURMUR_ATTACK = AMSoundRegistry.createSoundEvent("murmur_attack");
    public static final RegistryObject<SoundEvent> MURMUR_ANGER = AMSoundRegistry.createSoundEvent("murmur_anger");
    public static final RegistryObject<SoundEvent> TENDON_WHIP = AMSoundRegistry.createSoundEvent("tendon_whip");
    public static final RegistryObject<SoundEvent> SKUNK_HURT = AMSoundRegistry.createSoundEvent("skunk_hurt");
    public static final RegistryObject<SoundEvent> SKUNK_IDLE = AMSoundRegistry.createSoundEvent("skunk_idle");
    public static final RegistryObject<SoundEvent> SKUNK_SPRAY = AMSoundRegistry.createSoundEvent("skunk_spray");
    public static final RegistryObject<SoundEvent> STINK_RAY = AMSoundRegistry.createSoundEvent("stink_ray");
    public static final RegistryObject<SoundEvent> BANANA_SLUG_HURT = AMSoundRegistry.createSoundEvent("banana_slug_hurt");
    public static final RegistryObject<SoundEvent> BANANA_SLUG_SLIME_EXPAND = AMSoundRegistry.createSoundEvent("banana_slug_slime_expand");
    public static final RegistryObject<SoundEvent> BLUE_JAY_IDLE = AMSoundRegistry.createSoundEvent("blue_jay_idle");
    public static final RegistryObject<SoundEvent> BLUE_JAY_HURT = AMSoundRegistry.createSoundEvent("blue_jay_hurt");
    public static final RegistryObject<SoundEvent> BLUE_JAY_SONG = AMSoundRegistry.createSoundEvent("blue_jay_song");
    public static final RegistryObject<SoundEvent> CAIMAN_IDLE = AMSoundRegistry.createSoundEvent("caiman_idle");
    public static final RegistryObject<SoundEvent> CAIMAN_HURT = AMSoundRegistry.createSoundEvent("caiman_hurt");
    public static final RegistryObject<SoundEvent> CAIMAN_SPLASH = AMSoundRegistry.createSoundEvent("caiman_splash");
    public static final RegistryObject<SoundEvent> TRIOPS_HURT = AMSoundRegistry.createSoundEvent("triops_hurt");
    public static final RegistryObject<SoundEvent> END_PIRATE_DOOR = AMSoundRegistry.createSoundEvent("end_pirate_door");

    private static RegistryObject<SoundEvent> createSoundEvent(String soundName) {
        return DEF_REG.register(soundName, () -> SoundEvent.m_262824_((ResourceLocation)new ResourceLocation("alexsmobs", soundName)));
    }
}

